// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9b5329839558a78550bf078c3e5f323c2f0f3b86/react-hot-loader/index.d.ts
declare module 'react-hot-loader' {
// Type definitions for react-hot-loader 3.0
// Project: https://github.com/gaearon/react-hot-loader
// Definitions by: Jacek Jagiello <https://github.com/jacekjagiello/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

import * as React from 'react'

interface ErrorReporterProps {
  error: any
}

export interface AppContainerProps {
  children?: React.ReactElement<any>,
  errorReporter?: React.ComponentClass<ErrorReporterProps> | React.StatelessComponent<ErrorReporterProps>
}

export class AppContainer extends React.Component<AppContainerProps, {}> {}
}
